### PR TITLE
Add Docker Env Variables for Machinery Host and Port

### PR DESCRIPTION
**Pull request by wcomartin**

### CODE REVIEW

**Comment by cedricve** [comment]
nice @wcomartin, just a thought can these ENV been override using docker-compose.yml?

**Comment by wcomartin** [comment]
maybe i've never used docker-compose, and i dont think that would work if you were pulling the image directly from dockerhub?

**Comment by shacal** [comment]
Why you wanna change port? Just expose port if you need.

```
    ports:
    - 8889:8880/tcp
```

**Comment by cedricve** [comment]
@wcomartin, I think @shacal is right.

**Comment by wcomartin** [comment]
I think your missing the point of this PR, it's not for changing the exposed port for connecting to the Kerberos WEB its to define which port to connect to the Machinery on, if you have multiple machinery dockers running on the same host currently whenever i restart the container i need to go in and change the nginx config for the Web containers machinery route because this `proxy_pass http://machinery:8889;` hardcoded doesn't make sense

**Comment by Codex-** [comment]
A good flexible change that allows consumers to continue to use it without change, or offer a simple approach to changing the port. Sounds good to me.

**Comment by cedricve** [comment]
Looks good. Sorry missed this one.

**Pull request merged**
