### PR TITLE
Translate language pt-br

### PR DESCRIPTION
**Pull request by mikaelhadler**
Insert the translation file for language "Portuguese"

### CODE REVIEW

**Comment by cedricve** [comment]
Hey @mikaelhadler 

Would you like to expand your translation? We are finalizing the develop branch for production, and need to have the help of our contributors to translate some new keywords. You'll find the new translation attributes if you update your fork.

Call to action: https://github.com/kerberos-io/web/issues/74

**Comment by mikaelhadler** [comment]
Hey @cedricve 

Yes, do you have the section modified with depend of translate?

**Comment by cedricve** [comment]
hey @mikaelhadler, yes you'll see /** to do **/ in front of the words.

**Comment by mikaelhadler** [comment]
Right, i go work in this week, for when this release?

**Comment by mikaelhadler** [comment]
@cedricve i submitted this modifications.

**Pull request merged**
