### PR TITLE
Translated to french

### PR DESCRIPTION
**Pull request by Orabig**

### CODE REVIEW

**Comment by cedricve** [comment]
Good job, looks good :+1:

**Comment by cedricve** [comment]
Hey @Orabig 

Would you like to expand your translation? We are finalizing the develop branch for production, and need to have the help of our contributors to translate some new keywords. You'll find the new translation attributes if you update your fork.

Call to action: https://github.com/kerberos-io/web/issues/74

**Comment by Orabig** [comment]
Hi,

Sure.

I'm sorry, because my Raspberry is dead since several months now, so I
couldn't help you on this project, but I can certainly help on
translation...

I'm on it !

2017-01-27 11:59 GMT+01:00 Cédric Verstraeten <notifications@github.com>:

**Comment by cedricve** [comment]
No problem @Orabig, glad to hear you want to help! 👍

**Pull request merged**
