### PR TITLE
Bulgarian translation (bg-bg)

### PR DESCRIPTION
**Pull request by achuchev**
Bulgarian translation and minor fixes in English.

### CODE REVIEW

**Comment by cedricve** [comment]
perfect @achuchev! great PR

**Comment by cedricve** [comment]
Is it possible to send this PR to our develop branch?

**Comment by achuchev** [comment]
Hi. I'm still sleeping, but it is for kerberos-io:develop, right?

**Comment by cedricve** [comment]
@achuchev my bad. I've merged your PR.

**Pull request merged**
