### PR TITLE
Translating web interface for pt-br

### PR DESCRIPTION
**Pull request by mikaelhadler**

### CODE REVIEW

**Comment by cedricve** [comment]
looks like you've used an old branch..

**Comment by mikaelhadler** [comment]
But,the 'develop' branch no is a actually repositorie for this release?

**Comment by mikaelhadler** [comment]
Have more information @cedricve ?

**Comment by cedricve** [comment]
@mikaelhadler well should update your fork first, then you'll see the new translation files over here.. Tell me if you need more help.

**Pull request closed without merging**
