### PR TITLE
Add support in web for Swedish language

### PR DESCRIPTION
**Pull request by APayerl**
Done all translation files for swedish language except the `validation.php` one.. not sure how those fields get used...

### CODE REVIEW

**Comment by APayerl** [comment]
For some reason I got a couple of commits made by you @cedricve ... not sure how they appeared in my branch...

**Comment by cedricve** [comment]
Hello @APayerl thanks for your awesome work! Could you pull latest changes from develop, I made some alignments with master branch. So the docker changes in your PR will dissapear.

**Comment by APayerl** [comment]
@cedricve Done!
Though as I said, validation.php is not translated... could you maybe explain a bit in what context that file is used so I could understand how to translate it? Specificly what is an attribute in its' context?

**Comment by cedricve** [comment]
Alright good to go! Thanks.

You are mentioned as contributor here: https://github.com/kerberos-io/web/issues/74

**Comment by cedricve** [comment]
@APayerl it is actually not used in our web application it is a default Laravel file. No worries ;) Great work here!

**Pull request merged**
